import assert from 'node:assert/strict';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { chromium } from 'playwright';
import { createApplication } from '../src/main.ts';
import { loadConfig } from '../src/config.ts';

const root = await mkdtemp(join(tmpdir(), 'vloer-browser-'));
const previousDataDir = process.env.VLOER_DATA_DIR;
process.env.VLOER_DATA_DIR = join(root, 'demo');
const demoConfig = loadConfig(['--demo']);
if (previousDataDir === undefined) delete process.env.VLOER_DATA_DIR;
else process.env.VLOER_DATA_DIR = previousDataDir;
const app = await createApplication(demoConfig);
const password = randomBytes(24).toString('hex');
const live = await createApplication({ ...demoConfig, mode: 'live', dataDir: join(root, 'live'), litellm: undefined, runtime: { ...demoConfig.runtime, kind: 'opencode' }, auth: { ...demoConfig.auth, secureCookies: false, bootstrapName: 'browser-operator', bootstrapPassword: password } });
let browser;
const screenshots = process.env.VLOER_SCREENSHOTS ? resolve(process.env.VLOER_SCREENSHOTS) : undefined;
try {
  await Promise.all([new Promise(done => app.server.listen(0, '127.0.0.1', done)), new Promise(done => live.server.listen(0, '127.0.0.1', done))]);
  browser = await chromium.launch({ headless: true, ...(process.env.VLOER_CHROMIUM_BIN ? { executablePath: process.env.VLOER_CHROMIUM_BIN, args: ['--no-sandbox', '--no-zygote', '--single-process', '--disable-dev-shm-usage', '--disable-gpu'] } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1040 } });
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('401')) errors.push(message.text()); });
  const screenshot = async name => { if (screenshots) { await mkdir(screenshots, { recursive: true }); await page.screenshot({ path: join(screenshots, `${name}.png`), fullPage: true }); } };
  await page.goto(`http://127.0.0.1:${app.server.address().port}`);
  await page.getByRole('heading', { name: 'Sessions', exact: true }).first().waitFor();
  await screenshot('dashboard');
  await page.getByRole('button', { name: 'Run the demonstration' }).click();
  await page.getByText('Evidence is ready for your review.', { exact: true }).waitFor({ timeout: 25000 });
  await screenshot('session');
  await page.getByRole('tab', { name: /Changes/ }).click();
  await page.getByText('+  return Math.round((amount + Number.EPSILON) * 100);', { exact: true }).waitFor();
  await screenshot('changes');
  await page.getByRole('tab', { name: /Checks/ }).click();
  await page.getByRole('heading', { name: 'Baseline checks (expected failure)', exact: true }).waitFor();
  await page.getByRole('heading', { name: 'Independent review checks', exact: true }).waitFor();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export handoff' }).click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(), /^de-vloer-.*\.md$/);
  const downloadPath = await download.path();
  assert(downloadPath);
  await page.reload();
  await page.getByText('Evidence is ready for your review.', { exact: true }).waitFor();
  await page.getByRole('link', { name: 'All sessions' }).click();
  await page.getByRole('button', { name: /New session/ }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Create session' }).click();
  await page.getByRole('button', { name: 'Start crew' }).click();
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.getByRole('button', { name: 'Resume', exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Steer the next execution' }).fill('Preserve the invalid input checks and explain the scope of the rounding fix.');
  await page.getByRole('button', { name: 'Save instruction' }).click();
  await page.getByText('Next execution', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Resume', exact: true }).click();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel session' }).click();
  await page.getByText('Cancelled', { exact: true }).first().waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('link', { name: 'De Vloer home' }).click();
  await page.getByRole('heading', { name: 'Sessions', exact: true }).first().waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile layout overflows horizontally');
  await screenshot('mobile');
  await page.getByRole('link', { name: 'Environment' }).click();
  await page.getByRole('heading', { name: 'Execution environment', exact: true }).waitFor();
  await page.getByRole('link', { name: 'Ploeg queues' }).click();
  await page.getByRole('heading', { name: 'Connect your existing dispatch plane', exact: true }).waitFor();
  await page.setViewportSize({ width: 1440, height: 1040 });
  await page.goto(`http://127.0.0.1:${live.server.address().port}`);
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
  await screenshot('login');
  await page.getByRole('textbox', { name: 'Account name' }).fill('browser-operator');
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('heading', { name: 'Sessions', exact: true }).first().waitFor();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('heading', { name: 'Welcome back.' }).waitFor();
  assert.deepEqual(errors, [], 'Browser script or CSP errors occurred');
  process.stdout.write(`PASS: Chromium ${browser.version()}; demo, diff, checks, export, reload, create, pause, instruction, resume, cancel, mobile, navigation, live login/logout. No inference requests.\n`);
} finally {
  await browser?.close();
  await Promise.all([app.close(), live.close()]);
  await rm(root, { recursive: true, force: true });
}
